CREATE DATABASE ToDoCasa
GO

USE ToDoCasa
GO

CREATE TABLE Usuarios (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Email VARCHAR(255) NOT NULL,
	Senha VARCHAR(255) NOT NULL
)

CREATE TABLE Tarefas (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Titulo VARCHAR(255) NOT NULL,
	DataCriacao DATETIME NOT NULL,
)

CREATE TABLE TiposSubtarefas (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(255) NOT NULL
)

CREATE TABLE Subtarefas (
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Descricao VARCHAR(255) NOT NULL,
	Concluido BIT NOT NULL DEFAULT 0,
	TipoSubtarefaId INT NOT NULL FOREIGN KEY REFERENCES TiposSubtarefas(Id),
	TarefaId INT NOT NULL FOREIGN KEY REFERENCES Tarefas(Id)
)
